import hello from './api/hello.js';
import { goodbye, slow } from "./api/hello.js";
import { sendToIfttt } from './api/send.js';
import express from 'express';
import logger from 'morgan';
import sse from './api/sse.js';
import { corsMiddleware } from './middleware/cors.js';
import timeoutResponse from './middleware/timeout.js';
import swaggerUiExpress from 'swagger-ui-express';
// import { createRequire } from "module";
// const require = createRequire(import.meta.url);
// const swaggerDoc = require('./swagger-output.json');
import swagger from './api/docs.js';
// or use nodejs 17: import doc from './swagger-output.json' assert { type: 'json' };

const app = express();
const router = express.Router();
router.use(logger('dev'));
router.use(express.json()) ;
router.use(timeoutResponse);
router.use(corsMiddleware);
router.post("/hello", hello);
router.get("/bye", goodbye);
router.get("/slow", slow);
router.get("/send", sendToIfttt);
router.get("/sse", sse);
router.get("/", (req, res) => { res.send("Hello!") });
router.use("/docs", swaggerUiExpress.serve);
router.get("/docs", swagger);
const BASEPATH = "/api";
app.use(BASEPATH, router);
app.get("/", (req, res) => { res.send("Index") });

export default app;
export { BASEPATH };